### ISSUE TITLE
TypeError: str.charCodeAt is not a function

### ISSUE THREAD

**Issue by 3052** [glizzykingdreko/Datadome-Deobfuscator#1]
~~~
> node main.js ..\obf.js ..\deobf.js --rename
D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:96
    if (this._endsWithWord || str.charCodeAt(0) === 47 && this.endsWith(47)) {
                                  ^

TypeError: str.charCodeAt is not a function
    at Generator.word (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:96:35)
    at Generator.Identifier (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\types.js:35:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator._methodHead (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\methods.js:70:10)
    at Generator._classMethodHead (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\classes.js:160:8)
    at Generator.ClassMethod (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\classes.js:145:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.ClassBody (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\classes.js:61:10)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ClassDeclaration (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\classes.js:53:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.FunctionExpression (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\methods.js:109:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ObjectProperty (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\types.js:82:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.ObjectExpression (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\types.js:49:10)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ArrayExpression (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\types.js:92:12)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.CallExpression (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\generators\expressions.js:195:8)
    at Buffer.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\buffer.js:239:7)
    at Generator.exactSource (D:\Desktop\Datadome-Deobfuscator-main\node_modules\@babel\generator\lib\printer.js:163:15)

Node.js v21.1.0
~~~

**Comment by glizzykingdreko** [comment]
Can you please provide the input file you are using?

**Comment by 3052** [comment]
https://github.com/glizzykingdreko/Datadome-Deobfuscator/files/13259650/obf.txt

**Comment by glizzykingdreko** [comment]
Are you sure is a datadome file? can you link me the original source?

**Comment by 3052** [comment]
oh sorry I thought this was just a general deobfuscator. I dont even think the file is obfuscated, just minified. is that not supported? I would think it should work since its a valid JavaScript file

**Comment by glizzykingdreko** [comment]
"About
Tool to deobfuscate JavaScript files protected by Datadome. Decodes strings, simplifies code structure, and renames obfuscated identifiers for readability."

**Comment by 3052** [comment]
I found another option that works:

https://richsnapp.com/tools/code-unmangler
